server:
    port: 8080
spring:
    jpa:
      show-sql: true
      generate-ddl: true
      hibernate:
        ddl-auto: update
        naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://192.168.99.100:3306/phoneBook?createDatabaseIfNotExist=true
      username: root
      password: root